language: ruby
services:
  - docker
script:
  - docker build -t ndamiens/swagger-code-gen-sh .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
env:
  global:
  - secure: xf1DaRWg1cACuzYBgJiJnhA45ahNlWaTsfMs/NO4AHx5oPO6yLNAWm6BPYMS9OXTsULjYvCyWn9zx6eY/VDwxs3TCHF8UO0db595uKX59TdKbBgaWzTEdB3bCQWx7bhd5fmffQJJAXDutxBrMzJQLMcfBSQM8YMpMxT3aagajsYYBBV7PzAIwPkQx6btzxcZPi0E4EfGL8soJKSxtAWcb1juOg0uzqUJBylN6nFLShAmakWOTwVVzMiBH92sMeW6KMSDuBNqYlmir5c1pGii7GHDYy/J2qGN2TnoX2mzIm7rs48RDSZku16QNv+5zeWGXc7VNMQMne7ORsceMLbgjp5wUavjzCA1oqlAn7DK9CNHHr5f5HGz7fqc+z22CCxhPAj0RPBS3MNktNTPPdCxosT//mHO5nKNCW84Gr9y86CGdOF4TPCkfpvaPBha1Mz8hbRtCV3+5XIbrH5VqaWhLu3la4pANuf0oi630sP6t+fgu+e6XkSU8l4iT2zv3yugKBP3fO4h6q6OqWQO24md5iQg/oFyHyjQmCN6OkJ4An2fcEkpk339U1caNKg6ZhE+7RmG5cIkY3pAg5FoUfwFvI2eOL0+lGjIXZR+XF8By9xPhI0ezyT+V6bnAn4Sm5ORGt5e2f5z2mbdgH4o2JJ264Sk0jAiGHUCw21iQSwViLQ=
  - secure: 5xKbmP4p2RmlCZblEmEQ2lOpuEZHnTCARfaHsE8ipEBlvyfQ6+pTQe8hLjArkq55pzrbIimF7wDLGrlchnNR2ufk04tVHBzDOlhvipM3lDWuQAMufeXHei+Tk1DiAD8JW3pIpT8J9q6hrJq42fi6GIK4WoXgf4YGsuhCBH11Qt4Q/FQ0+Hj5Ug537VdT+yaB/oUL08hV3PXWL1cMG9VO/QKYzEHOO2HoXtHStJrv7XlItaYQa70/jd5eBFhvb2CXbHAxeYzD09R2c1sH7IYzRcF647Yp34wMpk81TV4gvSWIMTjU9VabH5GNDucTF24WDE3VrCQU54b1kDI+u3hymVycVKO8/bw6qNE/96mZBExsqfeCUJ1u65rESdC4lm2BpSTaMYwfqzyV/ckP5Djm4UwsVZcGDZlszzBkzrtNFUbB1GySFQvAbPxzeh46xNy/5EoNa6ecP7/mETf2t9AF/oN0wL1ipvAmLfw0TbWem0/wxhjbvXW1BATAdl94S18MpVILtXbWOEn/IZCAgkEJMgXX7SvhjVQWaLmrQFPuJNT3hnPaO7HIyJ0hUcD4tsCyEdZNuM6RSsJsmhsv0YROmEoucCqsiIbQWrsG9IlBLKgtlgiEGoUMhn5WgJth/a2HCoHThEL9mX2EsuFWpfXqaP+HId2LZ/I3XgR52ANkJRg=
